[features]
seeds = false
skip-lint = false
[programs.localnet]
scoreboard = "BBYN3Ss1Kw8vTKdiWooEhRQYLmENNXtGyrYHsZumj7jh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vonyi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


